kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
  - role: control-plane

    # O ingress-nginx para kind procura este label
    # para colocar o controller neste nó.
    labels:
      ingress-ready: "true"

    # Expõe as portas do nó kind no Mac.
    # Isso permite:
    #   http://app.localtest.me
    #   http://localhost
    #
    # sem port-forward.
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP

      - containerPort: 443
        hostPort: 443
        protocol: TCP